#!/usr/bin/env bash

# usage: run-tests "<cmd>"
#   e.g: run-tests "npm run tests"
output="$( $1 2> /dev/null )"
fail="$( echo "${output}" | grep "not ok" | head -1 | sed -E 's/^not ok [0-9]+ //')"
pass="$( echo "${output}" | grep "\.\." | head -1 )"
[[ -z "${fail}" ]] && title="Tests passed" || title="Tests failed"
[[ -z "${fail}" ]] && text="${pass}" || text="${fail}"
text="$( echo "${output}" | grep -oE "\S+\@\S+" | head -1 ) · ${text} tests"
clear
echo "${output}"
osascript -e "display notification \"$text\" with title \"$title\""
