#!/usr/bin/env bash

# usage: run-tests "<cmd>"
#   e.g: run-tests "npm run tests"
output="$( $1 2> /dev/null )"
fail="$( echo "${output}" | grep "not ok" | head -n 1)"
pass="$( echo "${output}" | grep "\.\." | head -n 1 )"
[[ -z "${fail}" ]] && title="Tests passed - $1" || title="Tests failed - $1"
[[ -z "${fail}" ]] && text="${pass}" || text="${fail}"
clear
echo "${output}"
osascript -e "display notification \"$text\" with title \"$title\""
